on:
  workflow_dispatch:
  push:
    branches: [master]
    paths-ignore:
      - "**/*.md"
      - "**/*.yml"
  pull_request:
    branches: [master]

name: Test on Linux
jobs:
  test-linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language: ["cpp"]

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.5
        with:
          submodules: recursive

      - name: Install build dependencies
        run: "sudo apt-get update && sudo apt-get install git build-essential cmake"

      - name: Compile
        run: "mkdir build && cd build && cmake .. -Dlockpp_tests=ON && cmake --build . --config Debug"

      - name: Run Tests
        run: "./build/tests/lockpp-tests"
